name: shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_auth: ^4.8.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  go_router: ^9.0.0
  hooks_riverpod: ^2.3.6
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  package_info: ^2.0.2
  path_provider: ^2.0.15
  sentry_flutter: ^7.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: 3.1.0+1
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/