// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWpMTl1-_WouhJfF24i8MlUZLBWDfHq7o',
    appId: '1:473857091927:web:af669d90689f9c63e13612',
    messagingSenderId: '473857091927',
    projectId: 'shop-a677d',
    authDomain: 'shop-a677d.firebaseapp.com',
    databaseURL: 'https://shop-a677d-default-rtdb.firebaseio.com',
    storageBucket: 'shop-a677d.appspot.com',
    measurementId: 'G-PVRL0SLLPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApaKlr_ZT2AygjZZHLGz1KVmRuuU1EGko',
    appId: '1:473857091927:android:9ad24a81f6f61c3fe13612',
    messagingSenderId: '473857091927',
    projectId: 'shop-a677d',
    databaseURL: 'https://shop-a677d-default-rtdb.firebaseio.com',
    storageBucket: 'shop-a677d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvkvXv0Z3g_7r-yEDCSvG62VwyaMVBpMo',
    appId: '1:473857091927:ios:ed77431b7b16cbcde13612',
    messagingSenderId: '473857091927',
    projectId: 'shop-a677d',
    databaseURL: 'https://shop-a677d-default-rtdb.firebaseio.com',
    storageBucket: 'shop-a677d.appspot.com',
    iosClientId: '473857091927-8codch6olcdaflt751m90h8kq1jih26f.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );
}
